#==========样例工程配置==========
#==========当需要修改框架默认参数时，可以复制 application-core.yml 中对应的配置内容进行修改==========
server:
  display-name: demo
  port: 8080
  context-path: /demo
  config:
    #是否开启系统配置热加载，默认false，不开启
    hotLoading: false
    #指定热加载的配置文件路径
    path: ${biz.conf.path}conf/demo.yml


#业务配置路径
biz:
  conf:
    path: /Users/home/Desktop/HJ/pureJ/biz/

#数据库类型：oracle、mysql、db2
jdbc:
  database:
    type: mysql
  #数据库连接
  url: jdbc:mysql://172.16.193.200:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
  username: root
  password: 123456
  #默认为mysql-8，如需其他版本请自行添加maven依赖，并修改DriverClass
  driver-Class-Name: com.mysql.cj.jdbc.Driver
