#==========当需要修改框架默认参数时，可以复制 application-core.yml 中对应的配置内容进行修改==========
server:
  display-name: cmdb
  port: 15910
  context-path: /cmdb
  config:
    hotLoading: false

biz:
  #是否开启业务配置热加载，默认true，开启
  hotLoading: false
  conf:
    path: /Users/home/Desktop/HJ/pureJ/biz/

#数据源配置
jdbc:
  mapper:
    #是否开启mapper文件热加载，默认true，开启
    hotLoading: false