server:
  display-name: pureJ
  port: 8080
  context-path: /pureJ
  config:
    #是否开启系统配置热加载，默认true，开启
    hotLoading: true
    #热加载的配置文件路径
    path: ${biz.conf.path}conf/app.yml

#业务配置路径
biz:
  #是否开启业务配置热加载，默认true，开启
  hotLoading: true
  conf:
    path: /Users/home/Desktop/HJ/pureJ/biz/
    service: ${biz.conf.path}channel/service/
    flow: ${biz.conf.path}channel/flow/
    converters: ${biz.conf.path}channel/converter/converters
    adapter: ${biz.conf.path}adapter/

#渠道服务配置
channel:
  service:
    success:
      #服务执行成功状态码，默认：0000
      code: '0000'
      msg: 服务执行成功
  flow:
    start:
      #服务流程开始索引，默认：1
      index: 1
  validate:
    #是否验证渠道服务输出数据，默认false，不验证
    output: false

#外部服务适配器配置
adapter:
  host: http://localhost:8080/pureJ/
  connectTimeout: 30000
  responseTimeout: 60000
  charset: UTF-8
  validate:
    #是否验证适配器服务数据数据，默认false，不验证
    output: false

#数据源配置
jdbc:
  database:
    #数据库类型：oracle、mysql、db2
    type: mysql
  mapper:
    #sql文件路径
    location: file:${biz.conf.path}mapper/${jdbc.database.type}/**/*.xml
    #是否开启mapper文件热加载，默认true，开启
    hotLoading: true
  #连接池配置
  initialSize: 5
  maxActive: 20
  minIdle: 5
  maxWait: 60000
  testOnBorrow: false
  testOnReturn: false
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 25200000
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: true
  filters: mergeStat
  #数据库连接
  url: jdbc:mysql://172.16.193.200:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
  username: root
  password: 123456
  driver-Class-Name: com.mysql.cj.jdbc.Driver
  validationQuery: SELECT 1 FROM dual

#日志配置
logging:
  file: ${server.display-name}.log
  level:
    org.springframework.web: ERROR
    com.lamb: DEBUG
  #日志配置
  #config: logback.xml
